### ISSUE TITLE
Замечания по 1 лабе

### ISSUE THREAD

**Issue by kazantsev-roman** [denis-bosiy/automata-theory#1]
## Код
1. Поправить именование функции. GetOutData не очень подходит для функции, которая преобразует данные одного автомата в другой и возвращает всё в csv виде
https://github.com/denis-bosiy/automata-theory/blob/90a2f7cf3d8360e2773889eb1b70527e110a2a62/MealyMooreConversion/Program.cs#L32

2. Данный if усложняет читаемость. Либо в GetInfoFromFile(string filePath) сделать обработку, если файл пуст и убрать данный if, либо сделать так (в обоих автоматах):
`if (csvData == "")
{
    return;
}
string[] dataLines =...`
https://github.com/denis-bosiy/automata-theory/blob/90a2f7cf3d8360e2773889eb1b70527e110a2a62/MealyMooreConversion/MealyMachineInfo.cs#L11

3. Действия с 0-м индексом можно вынести за цикл, а сам цикл начинать с 1, это уберет лишние проверки и увеличит читаемость кода (в обоих автоматах)
https://github.com/denis-bosiy/automata-theory/blob/90a2f7cf3d8360e2773889eb1b70527e110a2a62/MealyMooreConversion/MealyMachineInfo.cs#L16

## Алгоритм
1. Зачем усложнять? В Милли и в Мура ты делаешь split для данных, взятых из CSV, можно же просто возвращать из GetInfoFromFile массив строк, избавившись от split ты ненамного, но оптимизируешь свое приложение (в обоих автоматах)
https://github.com/denis-bosiy/automata-theory/blob/90a2f7cf3d8360e2773889eb1b70527e110a2a62/MealyMooreConversion/MealyMachineInfo.cs#L13

**Comment by denis-bosiy** [comment]
По поводу ифов на весь блок кода я бы так категорично не отзывался
Если добавлять в начале проверки, то мы будем противоречить принципам структурного программирования, будет трудно отладить потом функцию(к примеру, она возвратила говно. а в каком из ретурнов?)
Принципы структурного программирования: https://ru.wikipedia.org/wiki/%D0%A1%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%BD%D0%BE%D0%B5_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5
Статья про принцип: https://habr.com/ru/post/40841/

Поэтому избавляясь от вложенности кода мы приходим к другой проблеме, то есть качество кода в сумме не улучшается, поэтому в следующих заданиях замечания такого рода можно не писать

**Comment by denis-bosiy** [comment]
Все замечания исправлены, включая спорное(2-е в коде)
